# Generated by Django 5.2.7 on 2025-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidata',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='bidata',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='bidata',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
